table Medidas
	lineageTag: ac885a1d-e169-4810-ba19-fca7185d7bca

	measure 'Total de Salários' = SUM(Funcionario[SALÁRIO])
		lineageTag: b9c92005-2a58-4124-8139-a23783215443

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Funcionarios = COUNT(Funcionario[MATRÍCULA]) + 0
		formatString: 0
		lineageTag: c6461ba5-1af9-4b5b-b66e-3b631c01c48f

	measure 'Func. com Dependente' = DISTINCTCOUNT(Dependente[ID_MATRICULA]) + 0
		formatString: 0
		lineageTag: ef463d3b-dd82-4748-bbc3-8207e4a2f76b

	partition Medidas = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Coluna 1"})
				in
				    #"Colunas Removidas"

	annotation PBI_ResultType = Table

